import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { Tooltip, Button } from "@nextui-org/react";
import Image from "next/image";
import ArrowBackIosIcon from "@mui/icons-material/ArrowBackIos";
import ArrowForwardIosIcon from "@mui/icons-material/ArrowForwardIos";
import VolumeUpIcon from "@mui/icons-material/VolumeUp";
import VolumeOffIcon from "@mui/icons-material/VolumeOff";
import PauseIcon from "@mui/icons-material/Pause";
import PianoIcon from "@mui/icons-material/Piano";
import HourglassTopIcon from "@mui/icons-material/HourglassTop";
import QueueMusicIcon from "@mui/icons-material/QueueMusic";
import ShuffleIcon from '@mui/icons-material/Shuffle';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <header>
          <div className="Navheader">
            <p className="BrandName">"FSound.app"</p>
            <Button 
                radius="full"
                id="DonateCf"
                className="bg-gradient-to-tr from-pink-500 to-violet-400 text-white shadow-lg"
              >
                Donate me a Coffe
                <Image
                  width={30}
                  height={30}
                  src="/Material-image/coffee.png"
                  alt=""
                />
              </Button>
            <div className="Category">
              <Button
                radius="full"
                className="bg-gradient-to-tr from-pink-500 to-yellow-500 text-white shadow-lg"
              >
                Study
                <Image
                  width={30}
                  height={30}
                  src="/Material-image/study.png"
                  alt=""
                />
              </Button>
              <Button
                radius="full"
                className="bg-gradient-to-tr from-pink-500 to-yellow-500 text-white shadow-lg"
              >
                Working
                <Image
                  width={25}
                  height={25}
                  src="/Material-image/work.png"
                  alt=""
                />
              </Button>
              <Button
                radius="full"
                className="bg-gradient-to-tr from-pink-500 to-yellow-500 text-white shadow-lg"
              >
                Lofi
                <Image
                  width={28}
                  height={28}
                  src="/Material-image/lying.png"
                  alt=""
                />
              </Button>
              <Button
                radius="full"
                className="bg-gradient-to-tr from-pink-500 to-yellow-500 text-white shadow-lg"
              >
                Relax
                <Image
                  width={28}
                  height={28}
                  src="/Material-image/relax.png"
                  alt=""
                />
              </Button>
              <Button
                radius="full"
                className="bg-gradient-to-tr from-pink-500 to-yellow-500 text-white shadow-lg"
              >
                Coffe
                <Image
                  width={27}
                  height={27}
                  src="/Material-image/coffee-cup.png"
                  alt=""
                />
              </Button>
              <Button
                style={{ width: "120px" }}
                radius="full"
                className="  bg-gradient-to-tr from-pink-500 to-yellow-500 text-white shadow-lg"
              >
                Over Night
                <Image
                  width={20}
                  height={20}
                  src="/Material-image/moon.png"
                  alt=""
                />
              </Button>
            </div>
            <p className="Sayings">
              "Boost Your Focus, Feel Great and Relax with FSound"
            </p>
          </div>
        </header>
        <footer>
          <div className="ControlAll">
            <div className="ControlMusic">
              <Tooltip
                content={
                  <div className="key-control px-1 py-2">
                    <div className="text-small font-bold">Unmute</div>
                  </div>
                }
              >
                <Button variant="bordered">
                  <VolumeUpIcon></VolumeUpIcon>
                </Button>
              </Tooltip>

              <Tooltip
                content={
                  <div className="key-control px-1 py-2">
                    <div className="text-small font-bold">Mute</div>
                  </div>
                }
              >
                <Button variant="bordered">
                  <VolumeOffIcon></VolumeOffIcon>
                </Button>
              </Tooltip>

              <Tooltip
                content={
                  <div className="key-control px-1 py-2">
                    <div className="text-small font-bold">Shuff</div>
                  </div>
                }
              >
                <Button variant="bordered">
                  <ShuffleIcon></ShuffleIcon>
                </Button>
              </Tooltip>
              <div className="Control-Sound">
              <Tooltip
                content={
                  <div className="key-control px-1 py-2">
                    <div className="text-small font-bold">Back</div>
                  </div>
                }
              >
                <Button variant="bordered">
                  <ArrowBackIosIcon></ArrowBackIosIcon>
                </Button>
              </Tooltip>

              <Tooltip
                content={
                  <div className="key-control px-1 py-2">
                    <div className="text-small font-bold">Pause</div>
                  </div>
                }
              >
                <Button variant="bordered">
                  <PauseIcon></PauseIcon>
                </Button>
              </Tooltip>

              <Tooltip
                content={
                  <div className="key-control px-1 py-2">
                    <div className="text-small font-bold">Next</div>
                  </div>
                }
              >
                <Button variant="bordered">
                  <ArrowForwardIosIcon></ArrowForwardIosIcon>
                </Button>
              </Tooltip>
              </div>
              

              <Tooltip
                content={
                  <div className="key-control px-1 py-2">
                    <div className="text-small font-bold">Mix sounds</div>
                  </div>
                }
              >
                <Button variant="bordered">
                  <PianoIcon></PianoIcon>
                </Button>
              </Tooltip>

              <Tooltip
                content={
                  <div className="key-control px-1 py-2">
                    <div className="text-small font-bold">Pomodoro</div>
                  </div>
                }
              >
                <Button variant="bordered">
                  <HourglassTopIcon></HourglassTopIcon>
                </Button>
              </Tooltip>

              <Tooltip
                content={
                  <div className="key-control px-1 py-2">
                    <div className="text-small font-bold">Track List</div>
                  </div>
                }
              >
                <Button variant="bordered">
                  <QueueMusicIcon></QueueMusicIcon>
                </Button>
              </Tooltip>
            </div>

            
          </div>
        </footer>
        <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
      </body>
    </html>
  );
}
